In [2]:
import numpy as np

### np.array converts list to array

In [3]:
l1 = [1, 2, 3, 4]
np_1d_arr = np.array(l1)
np_1d_arr

array([1, 2, 3, 4])

In [4]:
l2 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
np_2d_arr = np.array(l2)
np_2d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### np.arange is similar to range in normal python

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.zeros returns an array of only zeros for the desired dimension

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones returns an array of only 1s for the desired dimension

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.linspace returns an equally spaced array

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### np.identity returns identity matrix

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.random functions
- np.random.rand(m,n) - returns random matrix of postive natural numbers
- np.random.randn(m,n) - returns random matrix of positive and negative natural numbers
- np.random.randint(1, 50) - returns random integer between the range

In [17]:
np.random.rand(5,5)

array([[0.06393007, 0.20002132, 0.24939779, 0.01470973, 0.85891921],
       [0.51614232, 0.0236942 , 0.40857539, 0.86538688, 0.58541386],
       [0.16756259, 0.2663426 , 0.8768338 , 0.46387626, 0.84822099],
       [0.49897069, 0.97420491, 0.46094438, 0.31830441, 0.09660892],
       [0.99801011, 0.82864336, 0.66317498, 0.23792129, 0.43170712]])

In [18]:
np.random.randn(5,5)

array([[-0.61111002,  1.36999633,  0.61724035,  2.30876401,  1.16684845],
       [-0.12877001,  0.8035    ,  1.77366825,  0.18522972,  0.84053784],
       [ 0.35681453,  0.74957218, -0.43383698, -0.09359202, -0.1415631 ],
       [-0.50641484,  1.23098559,  0.98256336, -0.89854496,  0.649971  ],
       [ 0.00365061, -0.14703759,  1.57177703,  1.06360616,  1.33716235]])

In [19]:
np.random.randint(5,100)

92

### Numpy Array Reshape - Reshapes an array to the required dimension. Condition being the total no of items remains the same in resulting dimension. It also cannot contain null values

In [21]:
myArr = np.arange(0,25)
myArr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
myArr.reshape(4,4) # This will raise an error as the dimension 4 * 4 does not match with the original 25

ValueError: cannot reshape array of size 25 into shape (4,4)

### np.argmax(array) returns the index of the maximum value in the array

In [28]:
np.argmax(myArr)

24

In [29]:
rand_ints = np.random.randint(5,100, (4,4))
rand_ints

array([[41, 57, 81, 68],
       [97, 73, 70, 36],
       [26, 53, 15, 96],
       [35, 14, 85, 48]])

In [32]:
np.argmax(rand_ints, axis=0) # Columns

array([1, 1, 3, 2], dtype=int64)

In [43]:

np.argmax(rand_ints, axis=1) # Rows

array([2, 0, 3, 2], dtype=int64)

In [33]:
rand_ints.transpose()

array([[41, 97, 26, 35],
       [57, 73, 53, 14],
       [81, 70, 15, 85],
       [68, 36, 96, 48]])