In [1]:
import numpy as np

### np.array converts list to array

In [2]:
l1 = [1, 2, 3, 4]
np_1d_arr = np.array(l1)
np_1d_arr

array([1, 2, 3, 4])

In [3]:
l2 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
np_2d_arr = np.array(l2)
np_2d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### np.arange is similar to range in normal python

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.zeros returns an array of only zeros for the desired dimension

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones returns an array of only 1s for the desired dimension

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.linspace returns an equally spaced array

In [9]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### np.identity returns identity matrix

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.random functions
- np.random.rand(m,n) - returns random matrix of postive natural numbers
- np.random.randn(m,n) - returns random matrix of positive and negative natural numbers
- np.random.randint(1, 50) - returns random integer between the range

In [11]:
np.random.rand(5,5)

array([[0.15058029, 0.15801067, 0.47041538, 0.40068707, 0.9610141 ],
       [0.84012971, 0.59315155, 0.77774682, 0.10939666, 0.01305138],
       [0.73948737, 0.07617129, 0.39235694, 0.95464904, 0.96671144],
       [0.39785894, 0.61284018, 0.11263764, 0.04656659, 0.1250588 ],
       [0.55929242, 0.26478904, 0.89901396, 0.6070419 , 0.45324367]])

In [12]:
np.random.randn(5,5)

array([[ 0.51684776,  0.53337219,  0.73731634,  0.85766092, -0.29406398],
       [-0.25918327,  0.53116001, -0.65090894,  0.24281111, -0.01245423],
       [-0.70488566, -0.09829952,  0.30833058, -0.95389052, -1.16544194],
       [ 0.50679474,  0.97284282,  1.46005205, -0.47596735, -0.30325878],
       [ 0.12679788, -1.81598132, -1.3160555 , -1.73898702, -1.61057766]])

In [13]:
np.random.randint(5,100)

24

### Numpy Array Reshape - Reshapes an array to the required dimension. Condition being the total no of items remains the same in resulting dimension. It also cannot contain null values

In [14]:
myArr = np.arange(0,25)
myArr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
myArr.reshape(4,4) # This will raise an error as the dimension 4 * 4 does not match with the original 25

ValueError: cannot reshape array of size 25 into shape (4,4)

### np.argmax(array) returns the index of the maximum value in the array

In [ ]:
np.argmax(myArr)

In [ ]:
rand_ints = np.random.randint(5,100, (4,4))
rand_ints

In [ ]:
np.argmax(rand_ints, axis=0) # Columns

In [ ]:

np.argmax(rand_ints, axis=1) # Rows

In [ ]:
rand_ints.transpose()