In [1]:
import numpy as np

In [2]:
my_array = np.random.randint(10, 100, 10)
my_array

array([34, 93, 94, 24, 70, 67, 78, 51, 68, 93])

### Array operations

In [3]:
print(my_array[3])
print(my_array[2:7])

24
[94 24 70 67 78]


### Copy in Numpy arrays

In [4]:
array_part = my_array[2:7]
# Replace all the items in an array
array_part[:] = 50
array_part

array([50, 50, 50, 50, 50])

In [5]:
# NOTE: It also replaces the items in the original array
my_array

array([34, 93, 50, 50, 50, 50, 50, 51, 68, 93])

In [6]:
# For replacing or copying items we should use copy function
copy_array = my_array[5:].copy()
copy_array

array([50, 50, 51, 68, 93])

In [7]:
copy_array[:] = 10
copy_array

array([10, 10, 10, 10, 10])

In [8]:
my_array

array([34, 93, 50, 50, 50, 50, 50, 51, 68, 93])

### 2D Arrays

In [9]:
my_2d_array = np.random.randint(10,30, (3,3))
my_2d_array

array([[29, 28, 29],
       [18, 15, 29],
       [14, 22, 23]])

In [10]:
print(my_2d_array[2][1])
print(my_2d_array[2,1]) 
print(my_2d_array[2]) # Selects entire 3rd row

22
22
[14 22 23]


In [11]:
# Creating submatrix
print(my_2d_array[:2,1:])
print(my_2d_array[:2,:2])
print(my_2d_array[1:,:2])
print(my_2d_array[1:,1:])

[[28 29]
 [15 29]]
[[29 28]
 [18 15]]
[[18 15]
 [14 22]]
[[15 29]
 [22 23]]


### Conditions in Numpy Array

In [12]:
new_array = np.random.randint(10,30, 10)
new_array

array([12, 17, 12, 12, 16, 29, 25, 24, 18, 16])

In [13]:
new_array > 15

array([False,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
# Select items of np array using conditions
new_array[new_array > 15]

array([17, 16, 29, 25, 24, 18, 16])

### Scaling matrix my multiplying or adding

In [15]:
new_array * 3

array([36, 51, 36, 36, 48, 87, 75, 72, 54, 48])

In [16]:
new_array + 2

array([14, 19, 14, 14, 18, 31, 27, 26, 20, 18])

In [17]:
new_array + new_array

array([24, 34, 24, 24, 32, 58, 50, 48, 36, 32])

In [18]:
np.mean(new_array)

18.1

In [19]:
np.median(new_array)

16.5

In [20]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
type(np.array([[[1]]]))

numpy.ndarray