In [1]:
import numpy as np

In [2]:
my_array = np.random.randint(10, 100, 10)
my_array

array([32, 23, 74, 34, 15, 30, 72, 16, 81, 39])

### Array operations

In [18]:
print(my_array[3])
print(my_array[2:7])

50
[50 50 50 50 50]


### Copy in Numpy arrays

In [19]:
array_part = my_array[2:7]
# Replace all the items in an array
array_part[:] = 50
array_part

array([50, 50, 50, 50, 50])

In [11]:
# NOTE: It also replaces the items in the original array
my_array

array([32, 23, 50, 50, 50, 50, 50, 16, 81, 39])

In [14]:
# For replacing or copying items we should use copy function
copy_array = my_array[5:].copy()
copy_array

array([50, 50, 16, 81, 39])

In [16]:
copy_array[:] = 10
copy_array

array([10, 10, 10, 10, 10])

In [17]:
my_array

array([32, 23, 50, 50, 50, 50, 50, 16, 81, 39])

### 2D Arrays

In [21]:
my_2d_array = np.random.randint(10,30, (3,3))
my_2d_array

array([[14, 24, 13],
       [19, 28, 26],
       [20, 11, 19]])

In [23]:
print(my_2d_array[2][1])
print(my_2d_array[2,1]) 
print(my_2d_array[2]) # Selects entire 3rd row

11
11
[20 11 19]


In [25]:
# Creating submatrix
print(my_2d_array[:2,1:])
print(my_2d_array[:2,:2])
print(my_2d_array[1:,:2])
print(my_2d_array[1:,1:])

[[24 13]
 [28 26]]
[[14 24]
 [19 28]]
[[19 28]
 [20 11]]
[[28 26]
 [11 19]]


### Conditions in Numpy Array

In [26]:
new_array = np.random.randint(10,30, 10)
new_array

array([16, 10, 15, 28, 21, 15, 26, 12, 29, 28])

In [28]:
new_array > 15

array([ True, False, False,  True,  True, False,  True, False,  True,
        True])

In [29]:
# Select items of np array using conditions
new_array[new_array > 15]

array([16, 28, 21, 26, 29, 28])

### Scaling matrix my multiplying or adding

In [33]:
new_array * 3

array([48, 30, 45, 84, 63, 45, 78, 36, 87, 84])

In [34]:
new_array + 2

array([18, 12, 17, 30, 23, 17, 28, 14, 31, 30])

In [35]:
new_array + new_array

array([32, 20, 30, 56, 42, 30, 52, 24, 58, 56])

In [36]:
np.mean(new_array)

20.0

In [37]:
np.median(new_array)

18.5

In [38]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
type(np.array([[[1]]]))

numpy.ndarray